// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "post": {
                "description": "create a new event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "create event",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PostEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.PostEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/board": {
            "get": {
                "description": "get events by group IDs for event board",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "get event board",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of group IDs",
                        "name": "group_ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecase.FetchEventBoardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/{event_id}/votes": {
            "post": {
                "description": "post a vote for an event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "post vote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PostVoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups": {
            "post": {
                "description": "create a new group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "create group",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PostGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.PostGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/join": {
            "post": {
                "description": "join a chosen group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "join group",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.JoinGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.JoinGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{group_id}": {
            "get": {
                "description": "get chosen group info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "get group info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "group_id",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GroupInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/groups/{group_id}/leave": {
            "post": {
                "description": "leave a chosen group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "leave group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "group_id",
                        "name": "group_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.LeaveGroupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "put": {
                "description": "update user information(icon, name)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "update user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/signin": {
            "post": {
                "description": "signin user from auth_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "signin user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SigninRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SigninResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/signup": {
            "post": {
                "description": "subscribe user to the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "subscribe user",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{user_id}/groups": {
            "get": {
                "description": "get user groups",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "groups"
                ],
                "summary": "get user groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user_id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/usecase.UserGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "middleware.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "usecase.EventBoardAuthor": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "author_name": {
                    "type": "string"
                }
            }
        },
        "usecase.EventBoardEvent": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/usecase.EventBoardAuthor"
                },
                "closing_time": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "group_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_all_day": {
                    "type": "boolean"
                },
                "latitude": {
                    "type": "string"
                },
                "location_name": {
                    "type": "string"
                },
                "longitude": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecase.EventBoardOption"
                    }
                },
                "start_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "usecase.EventBoardOption": {
            "type": "object",
            "properties": {
                "participant_count": {
                    "type": "integer"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "user_id": {
                                "type": "string"
                            },
                            "user_name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "usecase.FetchEventBoardResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecase.EventBoardEvent"
                    }
                }
            }
        },
        "usecase.GroupResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "group123"
                },
                "is_creator": {
                    "type": "boolean",
                    "example": true
                },
                "member_count": {
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "type": "string",
                    "example": "テストグループ"
                }
            }
        },
        "usecase.Member": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "usecase.UserGroup": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecase.GroupResponse"
                    }
                }
            }
        },
        "v1.GroupInfoResponse": {
            "type": "object",
            "required": [
                "group_members",
                "group_name",
                "manager_id",
                "password"
            ],
            "properties": {
                "group_members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/usecase.Member"
                    }
                },
                "group_name": {
                    "type": "string",
                    "example": "group_name"
                },
                "manager_id": {
                    "type": "string",
                    "example": "user_id"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "v1.JoinGroupRequest": {
            "type": "object",
            "required": [
                "group_name",
                "password",
                "user_id"
            ],
            "properties": {
                "group_name": {
                    "type": "string",
                    "example": "group_name"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "user_id": {
                    "type": "string",
                    "example": "user_id"
                }
            }
        },
        "v1.JoinGroupResponse": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "group123"
                }
            }
        },
        "v1.LeaveGroupRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "user_id": {
                    "type": "string",
                    "example": "user_id"
                }
            }
        },
        "v1.PostEventRequest": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "integer",
                    "example": 1000
                },
                "event_author_id": {
                    "type": "string",
                    "example": "user123"
                },
                "event_closing_date_time": {
                    "type": "string",
                    "example": "2023-09-30T23:59:59Z"
                },
                "event_description": {
                    "type": "string",
                    "example": "これはテストイベントです"
                },
                "event_end_date_time": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                },
                "event_id": {
                    "type": "string",
                    "example": "event123"
                },
                "event_location_name": {
                    "type": "string",
                    "example": "東京ドーム"
                },
                "event_message": {
                    "type": "string",
                    "example": "参加してください！"
                },
                "event_start_date_time": {
                    "type": "string",
                    "example": "2023-10-01T10:00:00Z"
                },
                "event_title": {
                    "type": "string",
                    "example": "テストイベント"
                },
                "group_id": {
                    "type": "string",
                    "example": "group123"
                },
                "latitude": {
                    "type": "number",
                    "example": 35.6895
                },
                "longitude": {
                    "type": "number",
                    "example": 139.6917
                }
            }
        },
        "v1.PostEventResponse": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string",
                    "example": "event123"
                }
            }
        },
        "v1.PostGroupRequest": {
            "type": "object",
            "required": [
                "description",
                "group_name",
                "manager_id",
                "password"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "description"
                },
                "group_name": {
                    "type": "string",
                    "example": "group_name"
                },
                "manager_id": {
                    "type": "string",
                    "example": "user_id"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                }
            }
        },
        "v1.PostGroupResponse": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "string",
                    "example": "group123"
                }
            }
        },
        "v1.PostVoteRequest": {
            "type": "object",
            "required": [
                "option",
                "user_id"
            ],
            "properties": {
                "option": {
                    "type": "string",
                    "example": "参加"
                },
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "v1.SigninRequest": {
            "type": "object",
            "required": [
                "auth_id"
            ],
            "properties": {
                "auth_id": {
                    "type": "string",
                    "example": "auth_id"
                }
            }
        },
        "v1.SigninResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "v1.SignupRequest": {
            "type": "object",
            "required": [
                "auth_id",
                "token",
                "user_name"
            ],
            "properties": {
                "auth_id": {
                    "type": "string",
                    "example": "auth_id"
                },
                "token": {
                    "type": "string",
                    "example": "fcm_token"
                },
                "user_icon": {
                    "type": "string",
                    "example": "user_icon"
                },
                "user_name": {
                    "type": "string",
                    "example": "user_name"
                }
            }
        },
        "v1.SignupResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "v1.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "user_icon": {
                    "type": "string",
                    "example": "https://example.com/icon.png"
                },
                "user_name": {
                    "type": "string",
                    "example": "user_name"
                }
            }
        },
        "v1.UpdateUserResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string",
                    "example": "user123"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chikokulympic-API",
	Description:      "This is a Chikokulympic server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
